---
- name: spring pet clinic
  hosts: all
  become: yes
  tasks:
    
  - name: ensure openjdk 11 available all the os
    ansible.builtin.package: 
      name: "{{ open_jdk }}"
      update_cache: "yes"
      state: present

  - name: create directory
    ansible.builtin.file:
      path: "{{ app_dir }}"
      state: directory 

  - name: download jar
    get_url: 
      url: "{{ download_url }}"
      dest: "{{ app_dir }}"

  - name: springpetclinicuser
    ansible.builtin.user:
      name: "{{ app_user }}"
      password: "{{ app_password }}"
      state: present

  - name: changing owner and permission
    ansible.builtin.file:
      path: "{{ app_dir }}/{{ app_jar }}"
      owner: springpetclinicuser
      group: springpetclinicuser
      mode: '0500'
      state: file

  - name: copy service file
    ansible.builtin.copy:
      src: springpetclinic.service
      dest: /etc/systemd/system/springpetclinic.service

  - name: enable and start service
    ansible.builtin.systemd:
      daemon_reload: "yes"

  - name: enable and start service
    ansible.builtin.systemd:
      name: springpetclinic.service
      state: started
      enabled: yes