---
- name: spring pet clinic
  hosts: all
  become: yes
  tasks:
  - name: os upgrade and cache update
    apt:
      update_cache: "yes"
      upgrade: "yes"
    
  - name: ensure openjdk 11 avilable
    apt: 
      name: openjdk-11-jdk
      state: present

  - name: create directory
    ansible.builtin.file:
      path: /usr/share/springpetclinic/
      state: directory 

  - name: download jar
    get_url: 
      url: https://rajshared.s3.amazonaws.com/spring-petclinic.jar
      dest: /usr/share/springpetclinic/
      force: no

  - name: springpetclinicuser
    ansible.builtin.user:
      name: springpetclinicuser
      password: springpetclinicuser
      state: present

  - name: changing owner and permission
    ansible.builtin.file:
      path: /usr/share/springpetclinic/spring-petclinic.jar
      owner: springpetclinicuser
      group: springpetclinicuser
      mode: '0500'
      state: file

  - name: copy service file
    ansible.builtin.copy:
      src: springpetclinic.service
      dest: /etc/systemd/system/springpetclinic.service

  - name: enable and start service
    ansible.builtin.systemd:
      daemon_reload: "yes"

  - name: enable and start service
    ansible.builtin.systemd:
      name: springpetclinic.service
      state: started
      enabled: yes