---
- name: tomcat installation on linux
  hosts: all
  become: yes
  tasks:
  - name: opanjdk 11 installation
    package: 
      name: "{{ java_package }}"
      state: present
      update_cache: "yes"

  - name: ensure tomcat group
    group:
      name: "{{ tomcat_group }}"
      state: present

  - name: ensure tomcat user
    user: 
      name: "{{ tomcat_user }}"
      shell: /bin/false
      group: "{{ tomcat_group }}"
      home: "{{ tomcat_home_dir }}"

  - name: download the tomcat 9
    get_url:
      url: "{{tomcat_url}}"
      dest: /tmp

  - name:
    ansible.builtin.unarchive:
      src: /tmp/apache-tomcat-9.0.54.tar.gz
      dest: "{{tomcat_home_dir}}"
      extra_opts:
      - --strip-components=1

  - name: /opt/tomcat dir permission update
    file:
      path: "{{tomcat_home_dir}}"
      owner: "{{tomcat_user}}"
      group: "{{tomcat_group}}"
      recurse: yes
      state: directory

  - name: conf dir group read and executive permision update
    file:
      path: "{{tomcat_home_dir}}/conf"
      mode: g+xr

  - name: service file copy
    copy:
      src: ./files/tomcat.service
      dest: /etc/systemd/system/tomcat.service

  - name: admin user permission update
    copy:
      src: ./files/tomcat-users.xml
      dest: /opt/tomcat/conf/tomcat-users.xml

  - name: master permission update
    copy:
      src: ./files/context.xml
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml
 
  - name: service enable and start
    ansible.builtin.systemd:
      name: tomcat
      state: started
      daemon_reload: yes
      enabled: yes
