# Ansible template for installing Apache2 on ubuntu server
---
- name: apache-installation
  hosts: all
  become: yes
  tasks:
    - name: update ubuntu and install apache
      apt: 
        name: apache2
        update_cache: yes
        state: present