---
# hosts is a inventory files used to select host machines to install application using ip address or dns name of the server
# group of the server 
all:
  vars:
    info_php_path: /var/www/html/info.php

  hosts:
  children:
    ubuntu:
      hosts:
#        192.168.56.105
#        192.168.56.101
         localhost
      vars:
        apache_package: apache2
        php_package:
        - php
        - php-mysql
        - libapache2-mod-php
    centos:
      vars:
        apache_package: httpd
        php_package:
        - php
        - php-mysql
        - php-fpm
      hosts:
        192.168.56.106
#    web-servers:
#      hosts:
#        xxx.xxx.xxx.xxx
#    db-server:
#      hosts:
#        xxx.xxx.xxx.xxx
